import re

from .memory import initialize_state, add_idea, state_to_dict
from .scorer import score_all_ideas, vote_best_ideas, choose_best_idea
from ..swarm_engine.api import execute_swarm_sync


class ChittiOrchestrator:
    def __init__(self, agent_count: int = 5):
        self.state = None
        self.agent_count = agent_count

    def initialize(self, problem: str):
        self.state = initialize_state(problem)
        return state_to_dict(self.state)

    def deduplicate_ideas(self):
        if self.state is None:
            return

        seen = set()
        unique_ideas = []

        for idea in self.state.ideas:
            normalized = idea.content.strip().lower()
            if normalized not in seen:
                seen.add(normalized)
                unique_ideas.append(idea)

        self.state.ideas = unique_ideas

    def extract_day_number(self, text: str):
        match = re.search(r"Day\s+(\d+)", text)
        return int(match.group(1)) if match else 999

    def clean_line(self, text: str):
        while "and connect it with the next day's topic and connect it with the next day's topic" in text:
            text = text.replace(
                "and connect it with the next day's topic and connect it with the next day's topic",
                "and connect it with the next day's topic"
            )

        while "with one hands-on mini project with one hands-on mini project" in text:
            text = text.replace(
                "with one hands-on mini project with one hands-on mini project",
                "with one hands-on mini project"
            )

        while "and include 1 hour of revision and include 1 hour of revision" in text:
            text = text.replace(
                "and include 1 hour of revision and include 1 hour of revision",
                "and include 1 hour of revision"
            )

        while "while focusing on practical implementation while focusing on practical implementation" in text:
            text = text.replace(
                "while focusing on practical implementation while focusing on practical implementation",
                "while focusing on practical implementation"
            )

        return text.strip()

    def synthesize_final_answer(self):
        if self.state is None or not self.state.ideas:
            return None

        sorted_ideas = sorted(
            self.state.ideas,
            key=lambda x: (x.score, x.votes, x.iteration),
            reverse=True
        )

        unique_by_day = {}

        for idea in sorted_ideas:
            day = self.extract_day_number(idea.content)
            cleaned = self.clean_line(idea.content)

            if day not in unique_by_day:
                unique_by_day[day] = cleaned

        final_lines = [unique_by_day[day] for day in sorted(unique_by_day.keys())]
        final_lines = [f"{i+1}. {line}" for i, line in enumerate(final_lines)]

        return "\n".join(final_lines)

    def run_iteration(self):
        raise NotImplementedError(
            "Dummy iteration flow has been disabled. Use run_real_swarm() for real AI execution."
        )

    def ingest_swarm_result(self, result_dict: dict):
        if self.state is None:
            self.initialize(result_dict["problem"])

        self.state.iteration = result_dict.get("iterations_run", self.state.iteration)

        for idea in result_dict.get("all_ideas", []):
            add_idea(
                state=self.state,
                content=idea.get("text", idea.get("content", "")),
                agent_name=f"swarm_agent_{idea.get('agent_id', 'x')}",
                iteration=idea.get("iteration", self.state.iteration),
                parent_ids=[],
                action_type="swarm_generated",
                reason=f"Generated by {idea.get('agent_style', 'unknown')} agent"
            )

        self.deduplicate_ideas()

        return {
            "final_output": result_dict.get("final_output", ""),
            "top_ideas": result_dict.get("top_ideas", []),
            "agent_summary": result_dict.get("agent_summary", []),
            "state": state_to_dict(self.state)
        }

    def run_real_swarm(self, num_iterations: int = 3):
        if self.state is None:
            raise ValueError("Chitti session not initialized")

        result = execute_swarm_sync(
            problem=self.state.problem,
            num_agents=self.agent_count,
            num_iterations=num_iterations,
            send_to_mcp=False
        )

        integrated = self.ingest_swarm_result(result.to_dict())

        score_all_ideas(self.state)
        vote_best_ideas(self.state)
        best = choose_best_idea(self.state)

        return {
            "best_idea": best.content if best else None,
            "final_output": result.final_output,
            "top_ideas": integrated["top_ideas"],
            "agent_summary": integrated["agent_summary"],
            "state": state_to_dict(self.state)
        }

    def score_and_vote(self):
        if self.state is None:
            raise ValueError("Chitti session not initialized")

        score_all_ideas(self.state)
        vote_best_ideas(self.state)
        best = choose_best_idea(self.state)
        final_output = self.synthesize_final_answer()

        return {
            "best_idea": best.content if best else None,
            "final_output": final_output,
            "state": state_to_dict(self.state)
        }

    def run_full_process(self, iterations: int = 3):
        return self.run_real_swarm(num_iterations=iterations)

    def get_state(self):
        if self.state is None:
            raise ValueError("Chitti session not initialized")

        return state_to_dict(self.state)